### ISSUE TITLE
Games i preordered are now locked

### ISSUE THREAD

**Issue by dem0z** [Zer0xFF/reactPSPLUS#1]
Okay now games i preorderd are locked, i preordered the last guardian and FF15 now both have the lock on them and can't play them, the PS plus games work fine though. meaning this only affects games you pre ordered so is there anyway to undo this?

**Comment by Zer0xFF** [comment]
If you're connected to the Internet you can go to settings, dates and update via Internet.

Eitherway, I'd release an undo payload to do that later tonight when I get home.

**Comment by dem0z** [comment]
Not possible being on 5.05 it asks to update to latest firmware.

**Comment by Zer0xFF** [comment]
I added a new payload which will set the date to today https://github.com/Thunder07/reactPSPLUS/releases/tag/0.1 note that the hours will be off, but thats only of concern to the internal clock, s it shouldnt be an issue at all.

once you confirm the issue is solved, please close this issue, Thanks.

**Comment by dem0z** [comment]
Thank you, works perfectly.
