### ISSUE TITLE
Trophies wrong date

### ISSUE THREAD

**Issue by Linasviel** [Zer0xFF/reactPSPLUS#2]
Hi i made the issue because i looked into my trophies and i found that the trophies are unlocked in wrong dates and if you know how to fix it i will appreciate you (i think that if you can explaining how to set a custom date in the payload will help to anyone).

**Comment by dem0z** [comment]
When you use the undo it reverts the date to 31st of may, then the internal clock counts from that.
Way to so sort that out is to set the internal clock to current date which am not sure how it can be done.

**Comment by Zer0xFF** [comment]
Thanks, I've been made aware of that, there is only 1 way I can think of to have a proper undo payload, and that is to modify the payload on the fly through javascript based on user selected date, it should be somewhat straight forward, calculate how many days it's been since 01/01/2012 until user selected dates in seconds.
```
var date1 = new Date(2012, 01, 01, 0, 0, 0);
var date2 = new Date(2018, 05, 31, hours, minutes, seconds); <-- these need to be made user selectable

var timetoset = (date2.getTime() - date1. getTime())/1000;
```
then we can set the value in the line that holds the seconds in the payload.

edit: also if you want to edit the payload with a different date it's just this line https://github.com/Zer0xFF/reactPSPLUS/blob/505/source/main.c#L20 that number represent time in seconds since 01/01/2012, so `6th of June 2018 07:30` would be `202807800`

**Comment by Linasviel** [comment]
Oh ok i will try it with the functions of javascript to obtain the seconds and compile the payload if i edit it successfully i will close the issue.

**Comment by Zer0xFF** [comment]
just to note, you should compile payload, convert it to JS, then modded it on the fly... something like this https://gist.github.com/Zer0xFF/d8bea77cdc44555af96f6e4cd8d56653

**Comment by Linasviel** [comment]
I compiled the payload with the real date in secs and it works perfectly thax for the help.
